<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'bn_name' => 'ড্যাশবোর্ড',
                'created_at' => '2023-03-19 14:04:30',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => 'uil-home-alt',
                'id' => 1,
                'is_hidden' => 'No',
                'name' => 'Dashboard',
                'order_by' => 1,
                'parent_id' => NULL,
                'route_name' => 'dashboard',
                'status' => 1,
                'system_name' => 'Dashboard',
                'updated_at' => '2023-05-03 06:24:30',
                'updated_by' => 1,
            ),
            1 => 
            array (
                'bn_name' => 'ইউজার ম্যানেজমেন্ট',
                'created_at' => '2023-03-19 18:06:39',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => 'fa fa-user',
                'id' => 2,
                'is_hidden' => 'No',
                'name' => 'User Management',
                'order_by' => 3,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'User Management',
                'updated_at' => '2023-05-07 05:51:36',
                'updated_by' => 1,
            ),
            2 => 
            array (
                'bn_name' => 'ইউজার',
                'created_at' => '2023-03-19 18:08:09',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 3,
                'is_hidden' => 'No',
                'name' => 'User',
                'order_by' => 1,
                'parent_id' => 2,
                'route_name' => 'user.index',
                'status' => 1,
                'system_name' => 'User',
                'updated_at' => '2023-03-31 18:10:57',
                'updated_by' => 1,
            ),
            3 => 
            array (
                'bn_name' => 'রোল ম্যানেজমেন্ট',
                'created_at' => '2023-03-19 18:14:26',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 4,
                'is_hidden' => 'No',
                'name' => 'Role Management',
                'order_by' => 4,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Role Management',
                'updated_at' => '2023-05-03 07:07:38',
                'updated_by' => 1,
            ),
            4 => 
            array (
                'bn_name' => 'রোল',
                'created_at' => '2023-03-19 18:17:21',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 5,
                'is_hidden' => 'No',
                'name' => 'Role',
                'order_by' => 1,
                'parent_id' => 4,
                'route_name' => 'role.index',
                'status' => 1,
                'system_name' => 'Role',
                'updated_at' => '2023-03-31 18:11:32',
                'updated_by' => 1,
            ),
            5 => 
            array (
                'bn_name' => 'মেন্যু ম্যানেজমেন্ট',
                'created_at' => '2023-04-03 10:38:48',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 25,
                'is_hidden' => 'No',
                'name' => 'Menu Management',
                'order_by' => 2,
                'parent_id' => NULL,
                'route_name' => '',
                'status' => 1,
                'system_name' => 'Menu Management',
                'updated_at' => '2023-04-03 10:38:48',
                'updated_by' => 1,
            ),
            6 => 
            array (
                'bn_name' => 'মেন্যু',
                'created_at' => '2023-04-03 10:39:32',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 26,
                'is_hidden' => 'No',
                'name' => 'Menu',
                'order_by' => 1,
                'parent_id' => 25,
                'route_name' => 'menu.index',
                'status' => 1,
                'system_name' => 'Menu',
                'updated_at' => '2023-04-03 10:39:32',
                'updated_by' => 1,
            ),
            7 => 
            array (
                'bn_name' => 'সফটওয়্যার সেটিংস',
                'created_at' => '2023-04-19 07:38:46',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 32,
                'is_hidden' => 'No',
                'name' => 'Software Settings',
                'order_by' => 21,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Software Settings',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            8 => 
            array (
                'bn_name' => 'কোম্পানি তথ্য',
                'created_at' => '2023-04-19 07:39:32',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 33,
                'is_hidden' => 'No',
                'name' => 'Company Information',
                'order_by' => 13,
                'parent_id' => 32,
                'route_name' => 'company.index',
                'status' => 1,
                'system_name' => 'Company Information',
                'updated_at' => '2023-04-19 07:39:32',
                'updated_by' => 1,
            ),
            9 => 
            array (
                'bn_name' => 'গ্রাহক তথ্য',
                'created_at' => '2023-04-19 07:40:33',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 34,
                'is_hidden' => 'No',
                'name' => 'Customer Information',
                'order_by' => 13,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Customer Information',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            10 => 
            array (
                'bn_name' => 'গ্রাহক যুক্ত করুন',
                'created_at' => '2023-04-19 07:41:20',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 35,
                'is_hidden' => 'No',
                'name' => 'Create Customer',
                'order_by' => 1,
                'parent_id' => 34,
                'route_name' => 'customer.create',
                'status' => 1,
                'system_name' => 'Create Customer',
                'updated_at' => '2023-06-11 07:03:02',
                'updated_by' => 1,
            ),
            11 => 
            array (
                'bn_name' => 'গ্রাহক দেখুন',
                'created_at' => '2023-04-29 06:36:51',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 36,
                'is_hidden' => 'No',
                'name' => 'Manage Customer',
                'order_by' => 2,
                'parent_id' => 34,
                'route_name' => 'customer.index',
                'status' => 1,
                'system_name' => 'Manage Customer',
                'updated_at' => '2023-06-11 07:03:02',
                'updated_by' => 1,
            ),
            12 => 
            array (
                'bn_name' => 'সাপ্লাইয়ার তথ্য',
                'created_at' => '2023-04-29 09:44:23',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 37,
                'is_hidden' => 'No',
                'name' => 'Supplier Information',
                'order_by' => 12,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Supplier Information',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            13 => 
            array (
                'bn_name' => 'সাপ্লাইয়ার যোগ করুন',
                'created_at' => '2023-04-29 09:45:16',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 38,
                'is_hidden' => 'No',
                'name' => 'Create Supplier',
                'order_by' => 1,
                'parent_id' => 37,
                'route_name' => 'supplier.create',
                'status' => 1,
                'system_name' => 'Create Supplier',
                'updated_at' => '2023-05-11 04:38:25',
                'updated_by' => 1,
            ),
            14 => 
            array (
                'bn_name' => 'সাপ্লাইয়ার দেখুন',
                'created_at' => '2023-04-29 10:30:41',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 39,
                'is_hidden' => 'No',
                'name' => 'Manage Supplier',
                'order_by' => 2,
                'parent_id' => 37,
                'route_name' => 'supplier.index',
                'status' => 1,
                'system_name' => 'Manage Supplier',
                'updated_at' => '2023-05-11 04:38:25',
                'updated_by' => 1,
            ),
            15 => 
            array (
                'bn_name' => 'প্রোডাক্ট সেটিংস',
                'created_at' => '2023-04-30 04:36:22',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 40,
                'is_hidden' => 'No',
                'name' => 'Product Settings',
                'order_by' => 15,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Product Settings',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            16 => 
            array (
                'bn_name' => 'আইটেম',
                'created_at' => '2023-04-30 04:37:07',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 41,
                'is_hidden' => 'No',
                'name' => 'Item',
                'order_by' => 25,
                'parent_id' => 40,
                'route_name' => 'item.index',
                'status' => 1,
                'system_name' => 'Item',
                'updated_at' => '2023-04-30 04:37:08',
                'updated_by' => 1,
            ),
            17 => 
            array (
                'bn_name' => 'ক্যাটাগরি',
                'created_at' => '2023-04-30 05:49:04',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 42,
                'is_hidden' => 'No',
                'name' => 'Category',
                'order_by' => 29,
                'parent_id' => 40,
                'route_name' => 'category.index',
                'status' => 1,
                'system_name' => 'Category',
                'updated_at' => '2023-05-01 04:58:07',
                'updated_by' => 1,
            ),
            18 => 
            array (
                'bn_name' => 'ব্রান্ড',
                'created_at' => '2023-05-01 04:58:07',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 43,
                'is_hidden' => 'No',
                'name' => 'Brand',
                'order_by' => 30,
                'parent_id' => 40,
                'route_name' => 'brand.index',
                'status' => 1,
                'system_name' => 'Brand',
                'updated_at' => '2023-05-01 04:58:07',
                'updated_by' => 1,
            ),
            19 => 
            array (
                'bn_name' => 'প্রোডাক্ট তথ্য',
                'created_at' => '2023-05-01 05:46:37',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 44,
                'is_hidden' => 'No',
                'name' => 'Product Information',
                'order_by' => 14,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Product Information',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            20 => 
            array (
                'bn_name' => 'পণ্য যুক্ত করুন',
                'created_at' => '2023-05-01 05:47:47',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 45,
                'is_hidden' => 'No',
                'name' => 'Add Product',
                'order_by' => 32,
                'parent_id' => 44,
                'route_name' => 'product.create',
                'status' => 1,
                'system_name' => 'Add Product',
                'updated_at' => '2023-06-06 08:54:33',
                'updated_by' => 1,
            ),
            21 => 
            array (
                'bn_name' => 'পরিমাপ',
                'created_at' => '2023-05-01 05:57:43',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 46,
                'is_hidden' => 'No',
                'name' => 'Measurement',
                'order_by' => 31,
                'parent_id' => 40,
                'route_name' => 'measurement.index',
                'status' => 1,
                'system_name' => 'Measurement',
                'updated_at' => '2023-05-01 05:57:43',
                'updated_by' => 1,
            ),
            22 => 
            array (
                'bn_name' => 'পণ্য দেখুন',
                'created_at' => '2023-05-01 07:04:09',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 47,
                'is_hidden' => 'No',
                'name' => 'Manage Product',
                'order_by' => 33,
                'parent_id' => 44,
                'route_name' => 'product.index',
                'status' => 1,
                'system_name' => 'Manage Product',
                'updated_at' => '2023-06-06 08:54:33',
                'updated_by' => 1,
            ),
            23 => 
            array (
                'bn_name' => 'ক্রয়',
                'created_at' => '2023-05-01 10:04:02',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 48,
                'is_hidden' => 'No',
                'name' => 'Purchase',
                'order_by' => 5,
                'parent_id' => NULL,
                'route_name' => 'purchase.create',
                'status' => 1,
                'system_name' => 'Purchase',
                'updated_at' => '2023-05-01 10:04:42',
                'updated_by' => 1,
            ),
            24 => 
            array (
                'bn_name' => 'মেজারমেন্ট সাবইউনিট',
                'created_at' => '2023-05-02 05:12:33',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 49,
                'is_hidden' => 'No',
                'name' => 'Measurement Sub Unit',
                'order_by' => 35,
                'parent_id' => 40,
                'route_name' => 'measurement_subunit.index',
                'status' => 1,
                'system_name' => 'Measurement Sub Unit',
                'updated_at' => '2023-05-02 05:12:34',
                'updated_by' => 1,
            ),
            25 => 
            array (
                'bn_name' => 'প্রোডাক্ট স্টক',
                'created_at' => '2023-05-03 06:24:30',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 51,
                'is_hidden' => 'No',
                'name' => 'Product Stock',
                'order_by' => 8,
                'parent_id' => NULL,
                'route_name' => 'stock.index',
                'status' => 1,
                'system_name' => 'Product Stock',
                'updated_at' => '2023-05-28 04:39:47',
                'updated_by' => 1,
            ),
            26 => 
            array (
                'bn_name' => 'সেলস',
                'created_at' => '2023-05-03 07:07:38',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 52,
                'is_hidden' => 'No',
                'name' => 'Sales',
                'order_by' => 7,
                'parent_id' => NULL,
                'route_name' => 'sales.create',
                'status' => 1,
                'system_name' => 'Sales',
                'updated_at' => '2023-05-28 04:39:47',
                'updated_by' => 1,
            ),
            27 => 
            array (
                'bn_name' => 'সেলস্ ইনফরমেশন',
                'created_at' => '2023-05-07 05:45:10',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 53,
                'is_hidden' => 'No',
                'name' => 'Sales Information',
                'order_by' => 9,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Sales Information',
                'updated_at' => '2023-05-28 04:39:47',
                'updated_by' => 1,
            ),
            28 => 
            array (
                'bn_name' => 'সেলস লেজার',
                'created_at' => '2023-05-07 05:45:43',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 54,
                'is_hidden' => 'No',
                'name' => 'Sales Ledger',
                'order_by' => 1,
                'parent_id' => 53,
                'route_name' => 'sales.index',
                'status' => 1,
                'system_name' => 'Sales Ledger',
                'updated_at' => '2023-05-07 05:45:43',
                'updated_by' => 1,
            ),
            29 => 
            array (
                'bn_name' => 'ক্রয় হিসাব',
                'created_at' => '2023-05-07 05:51:36',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 55,
                'is_hidden' => 'No',
                'name' => 'Purchase Information',
                'order_by' => 11,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Purchase Information',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            30 => 
            array (
                'bn_name' => 'ক্রয় লেজার সমূহ',
                'created_at' => '2023-05-07 05:52:16',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 56,
                'is_hidden' => 'No',
                'name' => 'Purchase Ledgers',
                'order_by' => 1,
                'parent_id' => 55,
                'route_name' => 'purchase.index',
                'status' => 1,
                'system_name' => 'Purchase Ledgers',
                'updated_at' => '2023-05-07 05:52:16',
                'updated_by' => 1,
            ),
            31 => 
            array (
                'bn_name' => 'সাপ্লাইয়ার পেমেন্ট',
                'created_at' => '2023-05-11 04:38:25',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 57,
                'is_hidden' => 'No',
                'name' => 'Supplier Payment',
                'order_by' => 3,
                'parent_id' => 37,
                'route_name' => 'supplier_payment.create',
                'status' => 1,
                'system_name' => 'Supplier Payment',
                'updated_at' => '2023-05-11 04:38:26',
                'updated_by' => 1,
            ),
            32 => 
            array (
                'bn_name' => 'কাস্টমার পেমেন্ট',
                'created_at' => '2023-05-12 14:49:53',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 58,
                'is_hidden' => 'No',
                'name' => 'Customer Payment',
                'order_by' => 3,
                'parent_id' => 34,
                'route_name' => 'customer_payment.create',
                'status' => 1,
                'system_name' => 'Customer Payment',
                'updated_at' => '2023-05-12 14:49:53',
                'updated_by' => 1,
            ),
            33 => 
            array (
                'bn_name' => 'আয় ব্যায় হিসাব',
                'created_at' => '2023-05-13 07:06:55',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 59,
                'is_hidden' => 'No',
                'name' => 'Income Expense Info',
                'order_by' => 16,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Income Expense Info',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            34 => 
            array (
                'bn_name' => 'আয় ব্যায় খাত',
                'created_at' => '2023-05-13 07:07:56',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 60,
                'is_hidden' => 'No',
                'name' => 'Income Expense Title',
                'order_by' => 1,
                'parent_id' => 59,
                'route_name' => 'income_expense_title.index',
                'status' => 1,
                'system_name' => 'Income Expense Title',
                'updated_at' => '2023-05-13 07:07:57',
                'updated_by' => 1,
            ),
            35 => 
            array (
                'bn_name' => 'আয় যোগ করুন',
                'created_at' => '2023-05-13 08:50:20',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 61,
                'is_hidden' => 'No',
                'name' => 'Add Income',
                'order_by' => 2,
                'parent_id' => 59,
                'route_name' => 'add_income.create',
                'status' => 1,
                'system_name' => 'Add Income',
                'updated_at' => '2023-05-13 08:50:20',
                'updated_by' => 1,
            ),
            36 => 
            array (
                'bn_name' => 'ব্যায় যোগ করুন',
                'created_at' => '2023-05-13 10:04:29',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 62,
                'is_hidden' => 'No',
                'name' => 'Add Expense',
                'order_by' => 3,
                'parent_id' => 59,
                'route_name' => 'add_expense.create',
                'status' => 1,
                'system_name' => 'Add Expense',
                'updated_at' => '2023-05-13 10:07:09',
                'updated_by' => 1,
            ),
            37 => 
            array (
                'bn_name' => 'ব্যাংক তথ্য',
                'created_at' => '2023-05-13 11:33:38',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 63,
                'is_hidden' => 'No',
                'name' => 'Bank Information',
                'order_by' => 17,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Bank Information',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            38 => 
            array (
                'bn_name' => 'ব্যাংক যোগ করুন',
                'created_at' => '2023-05-13 11:34:20',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 64,
                'is_hidden' => 'No',
                'name' => 'Add Bank',
                'order_by' => 1,
                'parent_id' => 63,
                'route_name' => 'add_bank.index',
                'status' => 1,
                'system_name' => 'Add Bank',
                'updated_at' => '2023-05-13 11:34:20',
                'updated_by' => 1,
            ),
            39 => 
            array (
                'bn_name' => 'ব্যাংক লেনদেন সমূহ',
                'created_at' => '2023-05-14 04:32:03',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 65,
                'is_hidden' => 'No',
                'name' => 'Bank Transaction',
                'order_by' => 2,
                'parent_id' => 63,
                'route_name' => 'bank_transaction.create',
                'status' => 1,
                'system_name' => 'Bank Transaction',
                'updated_at' => '2023-12-02 09:23:20',
                'updated_by' => 1,
            ),
            40 => 
            array (
                'bn_name' => 'কর্মচারীর তথ্য',
                'created_at' => '2023-05-14 09:49:16',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 66,
                'is_hidden' => 'No',
                'name' => 'Employee Information',
                'order_by' => 20,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Employee Information',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            41 => 
            array (
                'bn_name' => 'কর্মচারী যুক্ত করুন',
                'created_at' => '2023-05-14 09:50:12',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 67,
                'is_hidden' => 'No',
                'name' => 'Create Employee',
                'order_by' => 1,
                'parent_id' => 66,
                'route_name' => 'employee.index',
                'status' => 1,
                'system_name' => 'Create Employee',
                'updated_at' => '2023-05-14 09:50:12',
                'updated_by' => 1,
            ),
            42 => 
            array (
                'bn_name' => 'স্যালারি সেটআপ',
                'created_at' => '2023-05-15 09:25:43',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 68,
                'is_hidden' => 'No',
                'name' => 'Salary Setup',
                'order_by' => 2,
                'parent_id' => 66,
                'route_name' => 'salary_setup.index',
                'status' => 1,
                'system_name' => 'Salary Setup',
                'updated_at' => '2023-05-15 09:25:43',
                'updated_by' => 1,
            ),
            43 => 
            array (
                'bn_name' => 'স্যালারি পেমেন্ট',
                'created_at' => '2023-05-16 07:17:59',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 69,
                'is_hidden' => 'No',
                'name' => 'Salary Payment',
                'order_by' => 3,
                'parent_id' => 66,
                'route_name' => 'salary_withdraw.index',
                'status' => 1,
                'system_name' => 'Salary Payment',
                'updated_at' => '2023-05-16 07:18:00',
                'updated_by' => 1,
            ),
            44 => 
            array (
                'bn_name' => 'ঋণ তথ্য',
                'created_at' => '2023-05-17 04:53:12',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 70,
                'is_hidden' => 'No',
                'name' => 'Financial Loan Info',
                'order_by' => 18,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Loan Info',
                'updated_at' => '2023-12-03 05:44:46',
                'updated_by' => 1,
            ),
            45 => 
            array (
                'bn_name' => 'ঋণ রেজিষ্ট্রেশন',
                'created_at' => '2023-05-17 04:54:27',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 71,
                'is_hidden' => 'No',
                'name' => 'Loan Registration',
                'order_by' => 1,
                'parent_id' => 70,
                'route_name' => 'loan_registration.create',
                'status' => 1,
                'system_name' => 'Loan Registration',
                'updated_at' => '2023-05-17 04:54:27',
                'updated_by' => 1,
            ),
            46 => 
            array (
                'bn_name' => 'ঋণ গ্রহণ',
                'created_at' => '2023-05-17 08:36:48',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 72,
                'is_hidden' => 'No',
                'name' => 'Loan Recived',
                'order_by' => 2,
                'parent_id' => 70,
                'route_name' => 'loan_recived.create',
                'status' => 1,
                'system_name' => 'Loan Recived',
                'updated_at' => '2023-05-17 08:36:49',
                'updated_by' => 1,
            ),
            47 => 
            array (
                'bn_name' => 'ঋণ প্রদান',
                'created_at' => '2023-05-17 10:01:02',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 73,
                'is_hidden' => 'No',
                'name' => 'Loan Provide',
                'order_by' => 3,
                'parent_id' => 70,
                'route_name' => 'loan_provide.create',
                'status' => 1,
                'system_name' => 'Loan Provide',
                'updated_at' => '2023-06-07 06:24:50',
                'updated_by' => 1,
            ),
            48 => 
            array (
                'bn_name' => 'অভ্যন্তরীণ ঋণ',
                'created_at' => '2023-05-18 06:08:32',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 74,
                'is_hidden' => 'No',
                'name' => 'Internal Loan',
                'order_by' => 53,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Internal Loan',
                'updated_at' => '2023-12-17 05:03:58',
                'updated_by' => 1,
            ),
            49 => 
            array (
                'bn_name' => 'অভ্যন্তরীণ ঋণ রেজিষ্টার',
                'created_at' => '2023-05-18 06:09:22',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 75,
                'is_hidden' => 'No',
                'name' => 'Internal Loan Register',
                'order_by' => 1,
                'parent_id' => 74,
                'route_name' => 'internal_loanregister.index',
                'status' => 1,
                'system_name' => 'Internal Loan Register',
                'updated_at' => '2023-05-18 06:09:22',
                'updated_by' => 1,
            ),
            50 => 
            array (
                'bn_name' => 'অভ্যন্তরীণ ঋণ গ্রহণ',
                'created_at' => '2023-05-18 06:57:34',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 76,
                'is_hidden' => 'No',
                'name' => 'Internal Loan Recived',
                'order_by' => 2,
                'parent_id' => 74,
                'route_name' => 'internal_loan_recived.index',
                'status' => 1,
                'system_name' => 'Internal Loan Recived',
                'updated_at' => '2023-05-18 06:57:34',
                'updated_by' => 1,
            ),
            51 => 
            array (
                'bn_name' => 'অভ্যন্তরীণ ঋণ প্রদান',
                'created_at' => '2023-05-18 09:07:58',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 77,
                'is_hidden' => 'No',
                'name' => 'Internal Loan Provide',
                'order_by' => 3,
                'parent_id' => 74,
                'route_name' => 'internal_loan_provide.index',
                'status' => 1,
                'system_name' => 'Internal Loan Provide',
                'updated_at' => '2023-06-07 07:31:37',
                'updated_by' => 1,
            ),
            52 => 
            array (
                'bn_name' => 'ব্যাংক লেনদেন রিপোর্ট',
                'created_at' => '2023-05-25 06:09:05',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 78,
                'is_hidden' => 'No',
                'name' => 'Bank Transaction Report',
                'order_by' => 5,
                'parent_id' => 63,
                'route_name' => 'bank_trans_report.index',
                'status' => 1,
                'system_name' => 'Bank Transaction Report',
                'updated_at' => '2023-12-02 09:23:20',
                'updated_by' => 1,
            ),
            53 => 
            array (
                'bn_name' => 'ক্রয় এবং বিক্রয়',
                'created_at' => '2023-05-28 04:39:47',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 79,
                'is_hidden' => 'No',
                'name' => 'Purchase With Sales',
                'order_by' => 6,
                'parent_id' => NULL,
                'route_name' => 'purchase_with_sales.index',
                'status' => 1,
                'system_name' => 'Purchase With Sales',
                'updated_at' => '2023-05-28 04:39:47',
                'updated_by' => 1,
            ),
            54 => 
            array (
                'bn_name' => 'আয় ব্যায় রিপোর্ট',
                'created_at' => '2023-05-31 05:40:30',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 80,
                'is_hidden' => 'No',
                'name' => 'Income Expense Report',
                'order_by' => 4,
                'parent_id' => 59,
                'route_name' => 'income_expense_report.index',
                'status' => 1,
                'system_name' => 'Income Expense Report',
                'updated_at' => '2023-05-31 05:40:31',
                'updated_by' => 1,
            ),
            55 => 
            array (
                'bn_name' => 'ক্যাশ বুক',
                'created_at' => '2023-06-01 06:43:25',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 81,
                'is_hidden' => 'No',
                'name' => 'Cash Book',
                'order_by' => 33,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Cash Book',
                'updated_at' => '2023-12-17 05:03:58',
                'updated_by' => 1,
            ),
            56 => 
            array (
                'bn_name' => 'ক্যাশ ক্লোজ',
                'created_at' => '2023-06-01 06:44:42',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 82,
                'is_hidden' => 'No',
                'name' => 'Cash Close',
                'order_by' => 1,
                'parent_id' => 81,
                'route_name' => 'cash_close.index',
                'status' => 1,
                'system_name' => 'Cash Close',
                'updated_at' => '2023-06-01 06:44:42',
                'updated_by' => 1,
            ),
            57 => 
            array (
                'bn_name' => 'ক্যাশ ক্লোজ রিপোর্ট',
                'created_at' => '2023-06-04 10:20:32',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 83,
                'is_hidden' => 'No',
                'name' => 'Cash Close Report',
                'order_by' => 2,
                'parent_id' => 81,
                'route_name' => 'cash_close_report.index',
                'status' => 1,
                'system_name' => 'Cash Close Report',
                'updated_at' => '2023-06-04 10:20:33',
                'updated_by' => 1,
            ),
            58 => 
            array (
                'bn_name' => 'বারকোড',
                'created_at' => '2023-06-06 08:54:33',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 84,
                'is_hidden' => 'No',
                'name' => 'Product Barcode',
                'order_by' => 3,
                'parent_id' => 44,
                'route_name' => 'product_barcode.index',
                'status' => 1,
                'system_name' => 'Product Bacode',
                'updated_at' => '2023-06-06 08:54:33',
                'updated_by' => 1,
            ),
            59 => 
            array (
                'bn_name' => 'লোন রিপোর্ট',
                'created_at' => '2023-06-07 06:24:50',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 85,
                'is_hidden' => 'No',
                'name' => 'Loan Report',
                'order_by' => 4,
                'parent_id' => 70,
                'route_name' => 'loan_report.index',
                'status' => 1,
                'system_name' => 'Loan Report',
                'updated_at' => '2023-06-07 06:24:50',
                'updated_by' => 1,
            ),
            60 => 
            array (
                'bn_name' => 'অভ্যন্তরীণ ঋণ রিপোর্ট',
                'created_at' => '2023-06-07 07:31:37',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 86,
                'is_hidden' => 'No',
                'name' => 'Internal Loan Report',
                'order_by' => 4,
                'parent_id' => 74,
                'route_name' => 'internal_loan_report.index',
                'status' => 1,
                'system_name' => 'Internal Loan Report',
                'updated_at' => '2023-06-07 07:31:37',
                'updated_by' => 1,
            ),
            61 => 
            array (
                'bn_name' => 'কাস্টমার লেনদেন রিপোর্ট',
                'created_at' => '2023-06-11 07:03:02',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 87,
                'is_hidden' => 'No',
                'name' => 'Customer Transaction Report',
                'order_by' => 6,
                'parent_id' => 34,
                'route_name' => 'customer_trans_report.index',
                'status' => 1,
                'system_name' => 'Customer Transaction Report',
                'updated_at' => '2023-08-29 11:33:07',
                'updated_by' => 1,
            ),
            62 => 
            array (
                'bn_name' => 'সাপ্লাইয়ার লেনদেন তথ্য',
                'created_at' => '2023-06-14 10:37:52',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 89,
                'is_hidden' => 'No',
                'name' => 'Supplier Transaction Report',
                'order_by' => 4,
                'parent_id' => 37,
                'route_name' => 'supplier_trans_report.index',
                'status' => 1,
                'system_name' => 'Supplier Transaction Report',
                'updated_at' => '2023-06-14 10:37:52',
                'updated_by' => 1,
            ),
            63 => 
            array (
                'bn_name' => 'কাস্টমার লোন',
                'created_at' => '2023-08-29 11:33:46',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 91,
                'is_hidden' => 'No',
                'name' => 'Customer Loan',
                'order_by' => 7,
                'parent_id' => 34,
                'route_name' => 'customer_loan.index',
                'status' => 1,
                'system_name' => 'Customer Loan',
                'updated_at' => '2023-08-29 11:33:46',
                'updated_by' => 1,
            ),
            64 => 
            array (
                'bn_name' => 'সাপ্লাইয়ার লোন',
                'created_at' => '2023-08-29 11:35:14',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 93,
                'is_hidden' => 'No',
                'name' => 'Supplier Loan',
                'order_by' => 6,
                'parent_id' => 37,
                'route_name' => 'supplier_loan.index',
                'status' => 1,
                'system_name' => 'Supplier Loan',
                'updated_at' => '2023-08-29 11:35:14',
                'updated_by' => 1,
            ),
            65 => 
            array (
                'bn_name' => 'ক্রয় ফেরত',
                'created_at' => '2023-10-17 04:39:26',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 94,
                'is_hidden' => 'No',
                'name' => 'Purchase Return',
                'order_by' => 2,
                'parent_id' => 55,
                'route_name' => 'purchase_return.create',
                'status' => 1,
                'system_name' => 'Purchase Return',
                'updated_at' => '2023-10-17 04:39:26',
                'updated_by' => 1,
            ),
            66 => 
            array (
                'bn_name' => 'সেলস রিটার্ন',
                'created_at' => '2023-10-21 11:07:32',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 95,
                'is_hidden' => 'No',
                'name' => 'Sales Return',
                'order_by' => 2,
                'parent_id' => 53,
                'route_name' => 'sales_return.create',
                'status' => 1,
                'system_name' => 'Sales Return',
                'updated_at' => '2023-10-21 11:07:33',
                'updated_by' => 1,
            ),
            67 => 
            array (
                'bn_name' => 'সিসি লোন উত্তোলন',
                'created_at' => '2023-12-02 06:21:46',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 96,
                'is_hidden' => 'No',
                'name' => 'Withdraw CC Loan',
                'order_by' => 3,
                'parent_id' => 63,
                'route_name' => 'withdraw_cc_loan.index',
                'status' => 1,
                'system_name' => 'Withdraw CC Loan',
                'updated_at' => '2023-12-02 06:21:46',
                'updated_by' => 1,
            ),
            68 => 
            array (
                'bn_name' => 'ডিপোজিট সিসি লোন',
                'created_at' => '2023-12-02 09:23:20',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 97,
                'is_hidden' => 'No',
                'name' => 'Deposit CC Loan',
                'order_by' => 4,
                'parent_id' => 63,
                'route_name' => 'deposit_cc_loan.index',
                'status' => 1,
                'system_name' => 'Deposit CC Loan',
                'updated_at' => '2023-12-02 09:23:20',
                'updated_by' => 1,
            ),
            69 => 
            array (
                'bn_name' => 'অ্যাসেট তথ্য',
                'created_at' => '2023-12-13 05:10:14',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 99,
                'is_hidden' => 'No',
                'name' => 'Asset Info.',
                'order_by' => 27,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Asset Info',
                'updated_at' => '2023-12-13 05:10:14',
                'updated_by' => 1,
            ),
            70 => 
            array (
                'bn_name' => 'অ্যাসেট ক্যাটাগরি',
                'created_at' => '2023-12-13 05:12:07',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 100,
                'is_hidden' => 'No',
                'name' => 'Asset Category',
                'order_by' => 1,
                'parent_id' => 99,
                'route_name' => 'asset_category.create',
                'status' => 1,
                'system_name' => 'Asset Category',
                'updated_at' => '2023-12-13 05:12:07',
                'updated_by' => 1,
            ),
            71 => 
            array (
                'bn_name' => 'অ্যাসেট কস্ট',
                'created_at' => '2023-12-13 05:12:57',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 101,
                'is_hidden' => 'No',
                'name' => 'Asset Withdraw',
                'order_by' => 4,
                'parent_id' => 99,
                'route_name' => 'asset_cost.create',
                'status' => 1,
                'system_name' => 'Asset Cost Entry',
                'updated_at' => '2023-12-20 04:51:49',
                'updated_by' => 1,
            ),
            72 => 
            array (
                'bn_name' => 'Damage Product',
                'created_at' => '2023-12-14 09:19:15',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 105,
                'is_hidden' => 'No',
                'name' => 'Damage Products',
                'order_by' => 4,
                'parent_id' => 53,
                'route_name' => 'damage_product.create',
                'status' => 1,
                'system_name' => 'Damage Products',
                'updated_at' => '2023-12-14 09:19:15',
                'updated_by' => 1,
            ),
            73 => 
            array (
                'bn_name' => 'রিপোর্ট',
                'created_at' => '2023-12-17 05:03:58',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 106,
                'is_hidden' => 'No',
                'name' => 'Report',
                'order_by' => 28,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Report',
                'updated_at' => '2023-12-17 05:03:58',
                'updated_by' => 1,
            ),
            74 => 
            array (
                'bn_name' => 'স্টক রিপোর্ট',
                'created_at' => '2023-12-17 05:04:55',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 107,
                'is_hidden' => 'No',
                'name' => 'Stock Report',
                'order_by' => 1,
                'parent_id' => 106,
                'route_name' => 'stock_report.index',
                'status' => 1,
                'system_name' => 'Stock Report',
                'updated_at' => '2023-12-17 05:04:55',
                'updated_by' => 1,
            ),
            75 => 
            array (
                'bn_name' => 'সেলস প্রফিট রিপোর্ট',
                'created_at' => '2023-12-17 09:45:10',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 108,
                'is_hidden' => 'No',
                'name' => 'Sales Profit Report',
                'order_by' => 2,
                'parent_id' => 106,
                'route_name' => 'sales_profit.index',
                'status' => 1,
                'system_name' => 'Sales Profit Report',
                'updated_at' => '2023-12-17 09:45:10',
                'updated_by' => 1,
            ),
            76 => 
            array (
                'bn_name' => 'প্রফিট রিপোর্ট',
                'created_at' => '2023-12-18 06:50:45',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 109,
                'is_hidden' => 'No',
                'name' => 'Profit Report',
                'order_by' => 3,
                'parent_id' => 106,
                'route_name' => 'profit_report.index',
                'status' => 1,
                'system_name' => 'Profit Report',
                'updated_at' => '2023-12-18 06:50:45',
                'updated_by' => 1,
            ),
            77 => 
            array (
                'bn_name' => 'অ্যাসেট বিনিয়োগ',
                'created_at' => '2023-12-20 04:51:49',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 110,
                'is_hidden' => 'No',
                'name' => 'Asset Invest',
                'order_by' => 2,
                'parent_id' => 99,
                'route_name' => 'asset_invest.create',
                'status' => 1,
                'system_name' => 'Asset Invest',
                'updated_at' => '2023-12-20 04:51:49',
                'updated_by' => 1,
            ),
            78 => 
            array (
                'bn_name' => 'Asset Report',
                'created_at' => '2023-12-20 06:11:12',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 112,
                'is_hidden' => 'No',
                'name' => 'Asset Report',
                'order_by' => 4,
                'parent_id' => 106,
                'route_name' => 'asset_report.index',
                'status' => 1,
                'system_name' => 'Asset Report',
                'updated_at' => '2023-12-20 06:11:12',
                'updated_by' => 1,
            ),
        ));
        
        
    }
}